#!/data/data/com.termux/files/usr/bin/bash

set -e -u
#set -x

URL="$1"

quit() {
	echo "bye 👋"
	exit
}

while true
do
	echo "What should I do with "$URL"?"
	echo "y) download youtube video"
	echo "a) play youtube audio"
	echo "d) download as file"
	echo "x) nothing"

	read -p "Enter your choice: " CHOICE
	case "$CHOICE" in
		y)
			while true
			do
				read -p "Options? (x to exit) " OPTION
				if [ "$OPTION" == "x" ]
				then
					quit
				fi
				youtube-dl $OPTION "$URL"
			done
			;;
		a)
			mpsyt playurl "$URL"
			;;
	    d)
			axel -o "/storage/emulated/0/Download" "$URL"
			;;
	    x)
			quit
			;;
		*)
			echo "invalid choice. Try again."
			;;
	esac
done

